apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
      - name: engine
      # download nginx image from quaiy.io to avoid rate limits from Docker Hub
        image: quay.io/coreos/nginx:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: engine-service
spec:
  selector:
    app: engine
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080
  type: NodePort
