services:
  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my_network
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/eval"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    networks:
      - my_network
    volumes:
      - db_data:/var/lib/postgresql/data
networks:
  my_network:
    driver: bridge
volumes:
  db_data:
    driver: local