apiVersion: apps/v1
kind: Deployment
metadata:
 name: springboot-deployment
spec:
 replicas: 3
 selector:
   matchLabels:
     app: springboot
 template:
   metadata:
     labels:
       app: springboot
   spec:
     containers:
     - name: springboot
       image: 127.0.0.1:5000/my_sp:latest
       ports:
       - containerPort: 8080
